# Generated by Django 4.1.5 on 2023-02-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templates.crust'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templates.sauce'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templates.size'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templates.cheese'),
        ),
    ]
