# Generated by Django 4.1.5 on 2023-02-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_topping_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
