# Generated by Django 4.1.5 on 2023-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_pizza_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=150)),
                ('cardNum', models.CharField(blank=True, max_length=19)),
                ('cvv', models.CharField(blank=True, max_length=10)),
                ('expiration', models.DateField()),
            ],
        ),
    ]
