# Generated by Django 4.1.5 on 2023-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
