# Generated by Django 4.1.5 on 2023-02-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_order_address_alter_order_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templates.pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
