# Generated by Django 4.1.5 on 2023-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_order_pizza_alter_order_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='added',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='templates.topping'),
        ),
    ]
