# Generated by Django 4.1.5 on 2023-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_remove_topping_added_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
